title: Nicolás Castillo-Rodríguez
description: Academic website
url: "https://nicocastillorod.github.io"
baseurl: "https://nicocastillorod.github.io"

remote_theme: peterdesmet/petridish@3.1

plugins:
  - jekyll-remote-theme

markdown: kramdown
